name: Perform test checks

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
      - hotfix
      - release
    types: [opened, synchronize, reopened]

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run unit tests
        run: |
          echo "Run unit tests"

concurrency: # When we push something new in short succession in the same branch or PR, we cancel any previously-running job from that branch or PR so we don't pay to finish a job we no longer care about the outcome of.
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
