name: Perform complete checks on push

on:
  push:
    branches:
      - main
      - develop
      - hotfix
      - release
    paths-ignore: # Don't run the test suite on changes which are exclusively to:
      - 'README.md'

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run unit tests
        run: |
          echo "${{toJSON(github.event)}}"
          echo "Running unit tests"