name: Perform complete checks on push

on:
  push:
    branches:
      - main
      - develop
      - hotfix
      - release
    paths-ignore: # Don't run the test suite on changes which are exclusively to:
      - 'README.md'

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run unit tests
        run: |
          if [ "${{ github.event.commits }}" != "null" ]; then
            # The commits array is an array of commit objects describing the pushed commits.
            # A commit object has a property called "modified". "modified" is an array of files modified by the commit.
            # print the modified files for each commit.
            for commit in ${{ github.event.commits }}; do
              echo "Commit message: $commit.message"
              echo "Modified files: $commit.modified"
            done
          else
            echo "No commits found in the event."
          fi
          echo "Running unit tests"