name: Perform complete checks on master PR opened

on:
  push:
    branches:
      - main
    paths-ignore: # Don't run the test suite on changes which are exclusively to:
      - 'README.md'
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize]
    paths-ignore: # Don't run the test suite on changes which are exclusively to:
      - 'README.md'

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run unit tests
        run: |
          echo "${{toJSON(github.event)}}"
          echo "Running unit tests"

concurrency: # When we push something new in short succession in the same branch or PR, we cancel any previously-running job from that branch or PR so we don't pay to finish a job we no longer care about the outcome of.
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
