name: Perform complete checks

on:
  push:
    branches:
      - master
      - develop
      - hotfix
      - release

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run unit tests
        run: |
          echo "${{toJSON(github.event)}}"
          echo "Running unit tests"
          # make the step fail
          exit 1
  run-ui-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run UI tests
        run: |
          echo "${{toJSON(github.event)}}"
          echo "📲 Running UI tests"

concurrency: # When we push something new in short succession in the same branch, we cancel any previously-running job from that branch so we don't wait to finish a job we no longer care about the outcome of.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
